set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property PACKAGE_PIN W5 [get_ports mclk]
set_property PACKAGE_PIN V17 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports mclk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN W4 [get_ports {seg[11]}]
set_property PACKAGE_PIN V4 [get_ports {seg[10]}]
set_property PACKAGE_PIN U4 [get_ports {seg[9]}]
set_property PACKAGE_PIN U2 [get_ports {seg[8]}]
set_property PACKAGE_PIN V7 [get_ports {seg[7]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[2]}]


create_clock -period 100.000 -name mclk -waveform {0.000 50.000} [get_ports mclk]
create_generated_clock -name {div0/cnt_reg[1]_0[0]} -source [get_ports mclk] -divide_by 1 [get_pins {div0/cnt_reg[1]/Q}]

set_property PACKAGE_PIN W19 [get_ports {btn[4]}]
set_property PACKAGE_PIN T17 [get_ports {btn[3]}]


set_property PACKAGE_PIN T18 [get_ports {btn[2]}]
set_property PACKAGE_PIN U17 [get_ports {btn[1]}]
set_property PACKAGE_PIN U18 [get_ports {btn[0]}]

