# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/Documents/5puzzle/wagasha.cache/wt [current_project]
set_property parent.project_path Z:/Documents/5puzzle/wagasha.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo z:/Documents/5puzzle/wagasha.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  Z:/Documents/5puzzle/zf.v
  Z:/Documents/5puzzle/alu.v
  Z:/Documents/5puzzle/imem.v
  Z:/Documents/5puzzle/memory.v
  Z:/Documents/5puzzle/divider.v
  Z:/Documents/5puzzle/sel.v
  Z:/Documents/5puzzle/io.v
  Z:/Documents/5puzzle/pc.v
  Z:/Documents/5puzzle/register.v
  Z:/Documents/5puzzle/decoder.v
  Z:/Documents/5puzzle/top.v
  Z:/Documents/5puzzle/test.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top test -part xc7a35tcpg236-1


write_checkpoint -force -noxdef test.dcp

catch { report_utilization -file test_utilization_synth.rpt -pb test_utilization_synth.pb }
