# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/kanami/Documents/GitHub/5puzzle/wagasha.cache/wt [current_project]
set_property parent.project_path C:/Users/kanami/Documents/GitHub/5puzzle/wagasha.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/kanami/Documents/GitHub/5puzzle/wagasha.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/kanami/Documents/GitHub/5puzzle/alu.v
  C:/Users/kanami/Documents/GitHub/5puzzle/imem.v
  C:/Users/kanami/Documents/GitHub/5puzzle/memory.v
  C:/Users/kanami/Documents/GitHub/5puzzle/divider.v
  C:/Users/kanami/Documents/GitHub/5puzzle/sel.v
  C:/Users/kanami/Documents/GitHub/5puzzle/io.v
  C:/Users/kanami/Documents/GitHub/5puzzle/pc.v
  C:/Users/kanami/Documents/GitHub/5puzzle/register.v
  C:/Users/kanami/Documents/GitHub/5puzzle/decoder.v
  C:/Users/kanami/Documents/GitHub/5puzzle/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
